### ISSUE TITLE
Correct Login Fails after 2nd Attempt

### ISSUE THREAD

**Issue by cmanou** [auth0/auth0-ember-simple-auth#15] opened 2015-12-09 04:27 UTC
After 1 failed login, the next time you click access after correcting the login details, the popup closes and does not actually create the auth token or log you in. 

    "auth0-lock": "~7.12.5",
    "ember-simple-auth": "0.8.0",
    "ember": "1.13.7",
    "auth0-ember-simple-auth": "1.0.4",

Console Log is as follows, 
```
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (ro, line 0)
[Error] LoginError@http://localhost:4200/assets/vendor.js:78627:23
handleRequestError@http://localhost:4200/assets/vendor.js:76869:29
error@http://localhost:4200/assets/vendor.js:77900:25
http://localhost:4200/assets/vendor.js:80629:25
error@http://localhost:4200/assets/vendor.js:80707:36
http://localhost:4200/assets/vendor.js:80435:16
	console.error ([native code], line 0)
	onerrorDefault (vendor.js, line 42036)
	trigger (vendor.js, line 66212)
	_onerror (vendor.js, line 67178)
	publishRejection (vendor.js, line 65485)
	(anonymous function) (vendor.js, line 41997)
	invoke (vendor.js, line 10330)
	flush (vendor.js, line 10394)
	flush (vendor.js, line 10190)
	end (vendor.js, line 9580)
	(anonymous function) (vendor.js, line 10035)
```

**Comment by manuel-reil** [comment] 2015-12-29 18:37
Any updates on this?

In my case, I am locked in, so I can manually go to an AuthenticatedRoute without errors.
But the transition is not executed as sessionAuthenticated is not executed as authenticationSucceeded is not triggered.

After the failed login, I receive in the console:

    invalid_user_password: Wrong email or password.
    at LoginError.Error (native)
    at new LoginError (http://localhost:4200/assets/vendor.js:105174:19)
    at http://localhost:4200/assets/vendor.js:104372:23
    at onMessage (http://localhost:4200/assets/vendor.js:107703:17)

I guess this needs to be handled differently in the lock Authenticator, but still investigating.

**Versions:**
 - Ember             : 1.13.11
 - Ember Data        : 1.13.15
 - jQuery            : 2.1.4
 - Ember Simple Auth : 1.0.0

**Comment by brancusi** [comment] 2016-02-06 06:10
@manuel-reil, thank you, would you be up for creating a PR with this?

**Comment by psteininger** [comment] 2016-04-11 11:45
@manuel-reil thanks for the update. I was chasing this down for a few days now and even thought that the issue is with `ember-simple-auth`. I didn't think to look here.

What I found out is that `authenticationSucceeded` event is not fired and `ApplicationRouteMixin` doesn't call `sessionAuthenticated` method. I'll see if I got time today to trace this down more.

**Comment by psteininger** [comment] 2016-04-11 12:48
After digging around and experimenting, I realized the that calling reject is at the root of the problem. Calling reject, is closing the promise that actually opened the `Lock` widget. Therefore, nothing is going to listen to  that promise, since it's essentially dead (or perhaps more accurately, nothing will get to that closed promise). That's how I understand it. 

From a different view point. I thought about whether or not we should call `reject` here. And the answer is **no** as well. There is nothing we should do with the error from Lock. The UI is internally handled and message reaches the user. Perhaps we could add a callback to the authenticator like:
```javascript
onAuthError(error){
   return new Ember.RSVP.Promise();
}
```
and calling it in place of `reject`. This way the error isn't swallowed up, but it also doesn't break the login experience.

**Closed** 2016-04-12 21:23 UTC
